### ISSUE TITLE
Pupeteer error after updating to 1.1 on OSX

### ISSUE THREAD

**Issue by dhatch6** [camtheperson/get-my-ps5#23]
Running on OSX.
Pulled master (currently at 1.1)
Ran NPM install
Ran NPM run watch failed
deleted node modules and re-ran npm install/run watch but got the same error.

Previously worked yesterday before pulling 1.1

Error Message:
> get-my-ps5@1.1.0 watch /Users/user/Documents/workspace/get-my-ps5
> node index

/Users/User/Documents/workspace/get-my-ps5/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:707
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/Documents/workspace/get-my-ps5/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:19:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-my-ps5@1.1.0 watch: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get-my-ps5@1.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-12-11T18_25_36_215Z-debug.log

**Comment by dhatch6** [comment]
Had the same problem on windows. Realized my installed Node version is too far behind to work with the newest version of Pupeteer. Updated nodejs and script is working successfully now.
