### ISSUE TITLE
@camtheperson Please help will donate!!

### ISSUE THREAD

**Issue by drewdadon** [camtheperson/get-my-ps5#45]
@camtheperson please help me tried everthing to resolve these errors for hours nothing is working. Please help i will donate! 
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn bash
npm ERR! file bash
npm ERR! path bash
npm ERR! errno -4058
npm ERR! get-my-ps5@1.2.0 watch: `node ./src/index`
npm ERR! spawn bash ENOENT
npm ERR!
npm ERR! Failed at the get-my-ps5@1.2.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Drewski\AppData\Roaming\npm-cache\_logs\2020-12-13T07_32_19_755Z-debug.log

C:\Users\Drewski\Desktop\get-my-ps5>

**Comment by andrewfouad** [comment]
Error: Cannot find module 'puppeteer'
Require stack:
- C:\Users\Drewski\Desktop\get-my-ps5\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880
:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Drewski\Desktop\get-my-ps5\src\index.js:3:19
)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:1
0)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Drewski\\Desktop\\get-my-ps5\\src\\index.js'
[39m ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-my-ps5@1.2.0 watch: `node
./src/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the get-my-ps5@1.2.0
 watch script.
npm ERR! This is probably not a problem
 with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be
found in:
npm ERR!     C:\Users\Drewski\AppData\R
oaming\npm-cache\_logs\2020-12-13T07_42_00_869Z-debug.log

**Comment by andrewfouad** [comment]
Error: Cannot find module 'puppeteer'
Require stack:
- C:\Users\Drewski\Desktop\get-my-ps5\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:88
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Drewski\Desktop\get-my-ps5\src\index.j
)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_m
:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Drewski\\Desktop\\get-my-ps5\\src\\index.js'
}

npm ERR! Windows_NT 10.0.18363
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Drewski\\A
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v14.15.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! get-my-ps5@1.2.0 watch: `node ./src/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the get-my-ps5@1.2.0 watch script 'node ./src/index'.
npm ERR! Make sure you have the latest version of node.js and npm installe
npm ERR! If you do, this is most likely a problem with the get-my-ps5 pack
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./src/index
npm ERR! You can get information on how to open an issue for this project
npm ERR!     npm bugs get-my-ps5
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls get-my-ps5
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Drewski\Desktop\get-my-ps5\npm-debug.log

**Comment by drewdadon** [comment]
NVM i figured it out! you a goat

**Comment by drewdadon** [comment]
if works ill donate
